apiVersion: apps/v1
kind: Deployment
metadata:
  name: index
spec:
  replicas: 3
  selector:
    matchLabels:
      app: index
  template:
    metadata:
      labels:
        app: index
    spec:
      containers:
      - name: index-container
        image: quay.apps.ocp.komsco.co.kr/komsco/index:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: quay-registry-secret
