apiVersion: apps/v1
kind: Deployment
metadata:
  name: index
spec:
  selector:
    matchLabels:
      app: index
  template:
    metadata:
      labels:
        app: index
    spec:
      nodeSelector:
        dtarget: worker
      containers:
      - name: index-container
        image: quay.apps.ocp.komsco.co.kr/komsco/index:latest
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: quay-registry-secret
