apiVersion: apps/v1
kind: Deployment
metadata:
  name: demonstration
spec:
  selector:
    matchLabels:
      app: demonstration
  template:
    metadata:
      labels:
        app: demonstration
    spec:
      nodeSelector:
        dtarget: worker
      containers:
      - name: demonstration-container
        image: quay.apps.ocp.komsco.co.kr/komsco/demonstration:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: quay-registry-secret
