apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: app
spec:
  selector:
    app: my-app           # Pod의 label과 매칭
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080      # Pod의 containerPort와 일치
  type: ClusterIP
